model: YOLO #YOLO or RTDETR
model_name: MDV6-yolov9e.pt 
data: /home/v-druizlopez/ssdprivate/CameraTraps/PW_FT_detection/data/data_example.yaml # Fix to relative path
test_data: /home/v-druizlopez/ssdprivate/CameraTraps/PW_FT_detection/data/data_example/images/test # Fix to relative path
task: train
exp_name: MDV6-yolov9e

# Train
epochs: 20
batch_size_train: 16
imgsz: 640
device_train: 0
workers: 8
optimizer: auto
lr0: 0.01
patience: 5
save_period: 1
val: True
resume: False
weights: # Path to weight to resume training

# Validation
save_json: True
plot: True
device_val: 0
batch_size_val: 12




