# training
conf_id: Crop_Res18_plain_071824
algorithm: Plain
log_dir: Crop
num_epochs: 30
log_interval: 10
parallel: 0

# data
dataset_root: ./data/imgs
dataset_name: Custom_Crop
# annotation directory (if you have train/val/test splits)
annotation_dir: ./data/imgs
# data splitting (if you don't have train/val/test splits)
split_path: ./data/imgs/annotation_example.csv
test_size: 0.2
val_size: 0.2
split_data: True
split_type: location # options are: random, location, sequence
# data loading
batch_size: 32
num_workers: 4 #40
# model
num_classes: 2 
model_name: PlainResNetClassifier # options are: PlainResNetClassifier or RSGResNet
num_layers: 18
weights_init: ImageNet
loss_type: LDAM # options are: CE, LDAM, or Focal
# RSG
head_lists: [1,2,3,4,7,14,17,19,25] #classes with many samples
epoch_thresh: 150
n_center: 15
transfer_strength: 0.01

# optim
## feature
train_rule: DRW #options are: None, Reweight, or DRW
lr_feature: 0.01
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 10 # for StepLR scheduler in plain algo
milestones: [55, 75, 90] #for MultiStepLR scheduler in rsg algo
gamma: 0.1
